### ISSUE TITLE
Emby Image Pull

### ISSUE THREAD

**Issue by shadowsbane0** [kelinger/OmniStream#3] opened 2022-03-08 15:37 UTC
This may be a just me issue but image pull “emby/embyserver” fails on entry error. In all fairness it was doing that to me on Gooby as well. When I changed it to “lscr.io/linuxserver/emby:latest” I was good to go.

I don’t know why the official build is having an issue on my system. It could just be my setup. 

And yup I did figure out omni refresh resets the yaml files. I also did see the 800 section for personal and made the conclusion it would be for custom containers. I’m not sure if you will add any other insert option than dropping them in the components directory and letting docker-compose pick them up. It would be a feature request. 

I also get the variable scripts changed sometimes when Omni refreshes after I go in and change them to what I want similar to Gooby rewriting the /opt files where I previously would change what I needed. I can’t create a script from scratch to save my life but I can read one and reverse engineer what it is doing. I found what rclean.sh was doing and how/when the changes were being done.

**Comment by TechPerplexed** [comment] 2022-03-09 04:44
It's all fairly new to me as well (and no documentation yet, heh). But I think that the best way for custom containers would be to create the container in components.

Then activate it from the components menu, or using the shortcut `o+ <tab> <tab>`

Then run `omni up` to bring up your new container.

Rclean is no more, but been replaced by `omni upgrade` 🙂

**Comment by TechPerplexed** [comment] 2022-03-11 15:18
Well, I guess I'll close this too then... no one seems to have responded to the issue on Gooby, and again we can't reproduce it... and it seems your alternative image works. So I'll close this one as well then, and a you know... feel free to reopen :)

**Closed by TechPerplexed** 2022-03-11 15:18 UTC
