### ISSUE TITLE
Plex Token Claim - NZBget

### ISSUE THREAD

**Issue by oshamsi** [kelinger/OmniStream#20] opened 2022-10-07 14:45 UTC
Hi,
Been using Gooby for a while. excited for omnistreams potential. great work. gonna keep this short

Ran into a couple of issues:
1. Plex Token Claim: once installed plex via omni menu enabling the component then omni up, I never get asked to paste the claim token. I have the token copied but no option to paste. :)
2. after the installation of NZBGet and navigating to the app site, it'll ask for credintials that I dont have, tried the default, tried the one in the NZBget.conf file also, couldnt get it.

thanks for your support and I apologize if these are some dumb questions.

**Comment by oshamsi** [comment] 2022-10-07 15:29
Thanks ;) , I've been following you and Kelinger for awhile and appreciate both your amazing attitude and speed in supporting us. thanks.
So, for:
1. I Installed omnistream from scratch, your solution worked like a charm. Ya the screenshot is missing in that part :)))
2. this one didn't work still, so I tried every combination of username and password, didnt work, interestingly though, I installed sonarr, radarr and used your suggestion "admin" and the password that I setup... it logged in. but not NZBget. 

Any suggestions?

**Comment by TechPerplexed** [comment] 2022-10-07 15:32
I'll get back to you on NSBget - will install it from scratch and see if I can replicate your issue. First though I have my favorite appointment of the year: the dentist... wheee 🦷

**Comment by TechPerplexed** [comment] 2022-10-07 18:46
Thanks, well I just installed it and it's asking for the login like the Arrs (sounds rude, doesn't it) 😉 and using that, it opens just fine after that. So I'm not sure why it wouldn't work in your case. We'll troubleshoot some more and see if there is anything odd with that container setup in particular!

**Comment by oshamsi** [comment] 2022-10-07 19:02
It does😆. Thats's Weird, I did two fresh installs of omnistream just to double check, same issue. Ill continue to test as well. Also, am on debian11. dont know if that matters.

**Comment by kelinger** [comment] 2022-10-08 23:08
It looks like you're hitting the default NZBGet username/password prompts.  These are:

User:  nzbget
Password:  tegbzn6789

Once logged in, disable NZBget's authentication because you're using OmniStream's (and unless you've changed the config of OmniStream, you won't have any open ports that can bypass it).

I was able to reproduce your issue on a clean system and hit the same prompts as you.  The above credentials got me through it, though.

**Comment by oshamsi** [comment] 2022-10-09 07:23
I tried NZBget default creds however, that didn't work.
I gained access doing the following as a temp workaround:

1. omni down
2.  from components: edited the NZBGet YAML file to remove line traefik middleware oath
3. edited the NZBGet.config file to update the creds to match the other components.
4. omni up

I still don't know the reason behind that issue and why it didn't follow suite as the Arrs. I did add line mentioned in point 2 afterwards and that worked.

**Comment by TechPerplexed** [comment] 2022-10-09 16:33
Glad you found a solution, but I guess we'll still need to look at the original yaml file to see why it's behaving differently from the others. Meanwhile, since it's working for you, I'll close this ticket.

One important thing to note though: you shouldn't change the yaml file itself (201-etc), because you would prevent Omni from upgrading. You should copy the content into an 8xx-etc.yaml file instead, because that range is meant for custom containers. See this link for more information: https://www.omnistream.cloud/tips-tricks/custom-containers

Feel free to reopen this if you have additional questions/concerns :)

**Closed by TechPerplexed** 2022-10-09 16:33 UTC

**Comment by kelinger** [comment] 2022-10-10 18:46
As a test, I took a working system (using Oath but not NZBget) and enabled NZBget.  There was no previous config in the /configs directory so this was created brand new at startup.

When I did this, my experience was repeated.  The NZBget container stood up OK, the DNS was created and Traefik was configured to allow access.  When I went to the URL, I was again prompted with a browser popup for username and password.  It was here that the default NZBget credentials worked.  After I got in, I was able to disable the NZBget authentication using their setup.
