### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by DPMUC** [kelinger/OmniStream#12] opened 2022-05-10 19:07 UTC
Hey guys I love your project - even got Gooby etc...

now I wanted to try a new setup and I configured everything like you mentioned in your manual...

Got everything working, Rclone, Mounting etc...  setup Cloudflare... but I can't get it to work to get http://plex.mydomain etc. working...
but http://traefik.mydomain is working...
Everytime I get the "404 page not found" error... anything on that? what did I wrong in the configs??

Thanks so much...

**Comment by DPMUC** [comment] 2022-05-10 20:35
NAME                COMMAND                  SERVICE             STATUS                PORTS
autoheal            "/docker-entrypoint …"   autoheal            running (healthy)     
oauth               "./traefik-forward-a…"   oauth               running               
omnimount           "bash -c /root/start…"   omnimount           running (unhealthy)   
plex                "/init"                  plex                created               
portainer           "/portainer"             portainer           created               
traefik             "/entrypoint.sh --gl…"   traefik             running (healthy)     0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, :::80->80/tcp, :::443->443/tcp
watchtower          "/watchtower"            watchtower          running               8080/tcp

**Comment by DPMUC** [comment] 2022-05-10 20:36
sorry for the syntax...

**Comment by TechPerplexed** [comment] 2022-05-10 20:38
That's okay :) But it looks to me as if Plex isn't running yet because it seems that OmniMount didn't start properly. Can you try to restart omni (first `omni down` and then `omni up`) - what do get you get then?

**Comment by DPMUC** [comment] 2022-05-10 20:41
⠿ Network OmniNet       Created                                                                                                                                                                 0.1s
 ⠿ Container traefik     Healthy                                                                                                                                                                11.8s
 ⠿ Container oauth       Started                                                                                                                                                                 1.1s
 ⠿ Container autoheal    Started                                                                                                                                                                 1.0s
 ⠿ Container omnimount   Waiting                                                                                                                                                                11.8s
 ⠿ Container watchtower  Started                                                                                                                                                                 0.9s
 ⠿ Container portainer   Created                                                                                                                                                                 0.1s
 ⠿ Container plex        Created      



but omnimount needs a long time to go down und up...

**Comment by DPMUC** [comment] 2022-05-10 20:42
now omni status:

autoheal            "/docker-entrypoint …"   autoheal            running (healthy)    
oauth               "./traefik-forward-a…"   oauth               running              
omnimount           "bash -c /root/start…"   omnimount           running (starting)   
plex                "/init"                  plex                created              
portainer           "/portainer"             portainer           created              
traefik             "/entrypoint.sh --gl…"   traefik             running (healthy)    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, :::80->80/tcp, :::443->443/tcp
watchtower          "/watchtower"            watchtower          running              8080/tcp

**Comment by TechPerplexed** [comment] 2022-05-10 20:42
Ok wait a few minutes for it to start properly... does it comes up as healthy then?

**Comment by DPMUC** [comment] 2022-05-10 20:44
omnimount           "bash -c /root/start…"   omnimount           running (unhealthy)   

no still unhealthy...

**Comment by DPMUC** [comment] 2022-05-10 20:46
but the drive mount works...

**Comment by TechPerplexed** [comment] 2022-05-10 20:47
Bummer! Ok before we'll summon @kelinger can you try one last thing for me? Bring `omni down`, then `sudo reboot` your server and `omni up` - does it still come up as unhealthy then?

**Comment by DPMUC** [comment] 2022-05-10 20:51
i am on Debian 11... just by the way...

 ⠿ Network OmniNet       Created                                                                                                                                                                 0.0s
 ⠿ Container traefik     Healthy                                                                                                                                                                11.9s
 ⠿ Container omnimount   Waiting                                                                                                                                                                11.9s
 ⠿ Container watchtower  Started                                                                                                                                                                 1.0s
 ⠿ Container oauth       Started                                                                                                                                                                 1.3s
 ⠿ Container autoheal    Started                                                                                                                                                                 0.9s
 ⠿ Container plex        Created                                                                                                                                                                 0.1s
 ⠿ Container portainer   Created                                                                                                                                                                 0.1s
container for service "omnimount" is unhealthy

**Comment by TechPerplexed** [comment] 2022-05-10 20:54
Ok I'll send him a message to see if he has any ideas - heck I know he will, hehe. Stay tuned :)

**Comment by DPMUC** [comment] 2022-05-10 20:55
thanks... :)

**Comment by DPMUC** [comment] 2022-05-10 22:03
if I installed something like plex, portainer or any other container there is something missing in the docker-compose....
the first part (omnimount) is completely missing...
if I add only omnimount I see a correct docker-compose.yaml...

but how do I get omni up with a manual "corrected" docker-compose.yaml ???

**Comment by TechPerplexed** [comment] 2022-05-10 22:07
I'm not entirely sure what you are trying to do here. Before you mentioned you followed the instructions to get Omni running. That shouldn't involve any changes to any of the yaml files - definitely not in this stage. Can you please confirm that you have issues with a vanilla (out of the box) installation first?

I suggest you wipe your server and start from scratch. Then just get the basics running: Traefik and OmniMount. Is there any stage in the process where you get any errors?

**Comment by DPMUC** [comment] 2022-05-10 22:08
I did exactly this... new clean setup

there is no error if I just omni up omnimount and Traefik

**Comment by DPMUC** [comment] 2022-05-10 22:10
oauth               "./traefik-forward-a…"   oauth               running               
omnimount           "bash -c /root/start…"   omnimount           running (unhealthy)   
traefik             "/entrypoint.sh --gl…"   traefik             running (healthy)     0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, :::80->80/tcp, :::443->443/tcp


but also unhealthy

**Comment by DPMUC** [comment] 2022-05-10 22:12
even

omnimount           "bash -c /root/start…"   omnimount           running (unhealthy)   

only omnimount as container... with nothing else is unhealthy

**Comment by DPMUC** [comment] 2022-05-10 22:14
but still at this stage the mounting point works... got my drive under /mnt

**Comment by TechPerplexed** [comment] 2022-05-10 22:16
Ok :) We'll wait till kelinger comes in. I just wanted to make sure that you haven't made any changes to the setup or files just yet... it's rather hard to troubleshoot in that case :)

**Comment by kelinger** [comment] 2022-05-10 22:17
Until you get OmniMount working, there's no need to try any other components.  Is your rclone.conf in the ~/OmniStream/configs/omnimount directory?  What are the values of the variables used for MERGEMOUNT, MEDIA, RCLONESERVICE, RCLONEMOUNT, UNSYNCED, UPLOADCACHE ?

**Comment by DPMUC** [comment] 2022-05-10 22:20
yes, the file is there... but nano the file only shows my credentials (client-id etc.) which I entered...
the values you named aren't there...

**Comment by kelinger** [comment] 2022-05-10 22:23
No, the values I named won't be in that file but the file should be your rclone.conf.

For the values of the variables, type "echo $MERGEMOUNT" etc.  If they come back blank, then it looks like you didn't log out/in after installing.  If they aren't blank, what are they?

**Comment by DPMUC** [comment] 2022-05-10 22:26
stream@Debian-1011-buster-64-minimal:~/OmniStream/configs/omnimount$ echo $MERGEMOUNT
/home/stream/OmniStream/mnt/cloud
stream@Debian-1011-buster-64-minimal:~/OmniStream/configs/omnimount$ echo $MEDIA
/home/stream/OmniStream/mnt/cloud/Media
stream@Debian-1011-buster-64-minimal:~/OmniStream/configs/omnimount$ echo $RCLONESERVICE
gdrive
stream@Debian-1011-buster-64-minimal:~/OmniStream/configs/omnimount$ echo $RCLONEMOUNT
gdrive
stream@Debian-1011-buster-64-minimal:~/OmniStream/configs/omnimount$ echo $UNSYNCED
/home/stream/OmniStream/mnt/unsynced
stream@Debian-1011-buster-64-minimal:~/OmniStream/configs/omnimount$ echo $UPLOADCACHE
/home/stream/OmniStream/mnt/uploadcache

**Comment by kelinger** [comment] 2022-05-10 22:56
And the command "omni logs omnimount" ?

**Comment by DPMUC** [comment] 2022-05-10 22:58
omnimount  | rclone v1.58.1
omnimount  | - os/version: debian 11.3 (64 bit)
omnimount  | - os/kernel: 4.19.0-18-amd64 (x86_64)
omnimount  | - os/type: linux
omnimount  | - os/arch: amd64
omnimount  | - go/version: go1.17.9
omnimount  | - go/linking: static
omnimount  | - go/tags: none
omnimount  | 
omnimount  | mergerfs version: 2.33.5
omnimount  | 
omnimount  | Starting vnstat
omnimount  | 
omnimount  | Configuration:
omnimount  | MERGEMOUNT=cloud
omnimount  | RCLONESERVICE=gdrive
omnimount  | RCLONEMOUNT=gdrive
omnimount  | UNSYNCED=unsynced
omnimount  | UPLOADCACHE=uploadcache
omnimount  | MEDIA=Media
omnimount  | TURBOMAX=20
omnimount  | Adding group `omniuser' (GID 1000) ...
omnimount  | Done.
omnimount  | Adding user `omniuser' ...
omnimount  | Adding new user `omniuser' (1000) with group `omniuser' ...
omnimount  | Creating home directory `/home/omniuser' ...
omnimount  | Copying files from `/etc/skel' ...
omnimount  | Starting services
omnimount  | {
omnimount  | 	"jobid": 1
omnimount  | }
omnimount  | 
omnimount  | Startup complpete

**Comment by kelinger** [comment] 2022-05-10 23:16
Are you saying that you see the mounts in ~/omnistream/mnt and can access files in them?  What do you see in .../mnt/gdrive/Media ?

**Comment by DPMUC** [comment] 2022-05-10 23:22
this is my /mnt
cloud  gdrive  unsynced  uploadcache

/mnt/gdrive
is mounted to my "root" on Google - no gdrive/Media

But inside /mnt/gdrive/  I see my Root Folder and can browse the files...

think this is the failure? no Media folder in Google??

**Comment by kelinger** [comment] 2022-05-10 23:23
Correct.  Media needs to be at the root of your mount.  This can be fixed by mounting just above it (defining it as such in your rclone.conf).

**Comment by DPMUC** [comment] 2022-05-10 23:29
ok now its running healthy - and I try the rest of the setup... if its working now I say sorry for that one... - but Gooby worked with this setup... without changing my Rclone.conf...

sorry guys :)

**Comment by TechPerplexed** [comment] 2022-05-10 23:30
So when you type `omni status`, it shows healthy now? In that case, yes, it's working as intended. Omni is not Gooby - I'll be honest and say it's BETTER 🤣 But yeah, some things have changed a little in the upgrade...

**Comment by kelinger** [comment] 2022-05-10 23:40
Correct; there were some liberties taken with the paths since they are passed from the host to the container running the OmniMount process.  Since the full path outside of the container is not the same as the full path inside the container, we're looking at the basename of the path (ie, the final directory you're using).

**Closed** 2022-05-11 00:47 UTC

**Comment by DPMUC** [comment] 2022-05-11 01:25
Thank you very much - it worked fine now.... - last question:

my Plex server can't be claimed - it only comes to plex web... any idea ? thx so much...

**Comment by TechPerplexed** [comment] 2022-05-11 01:36
Sorry, that part of the tutorial (and process) is not streamlines yet, but try `setup-plex` and hopefully everything will speak for itself :)

**Comment by DPMUC** [comment] 2022-05-11 11:18
So i just wanna thank you both - everything is up now - and very smooth and simple… i like it sooo much… 
And again like always the most famous „bug“ is the human beeing…
I‘m Sorry for that and its a real pleasure to see your upcoming works/progresses… thanks again and have a nice day :)

**Comment by TechPerplexed** [comment] 2022-05-11 17:12
That's awesome to know :) As you probably know it's a brand new project - we haven't even gone fully live yet so always nice to know things are working as they should. Thanks for the feedback!
