### ISSUE TITLE
NetData DOA

### ISSUE THREAD

**Issue by shadowsbane0** [kelinger/OmniStream#2] opened 2022-03-08 15:25 UTC
NetData is DOA for me. Logs producing “ standard_init_linux.go:228: exec user process caused: no such file or directory” error. Was working on Gooby. Not working on Omni clean install.

**Comment by TechPerplexed** [comment] 2022-03-08 16:28
Hmm, strange, Shadow. Neither of us experienced any of those issues ourselves. Could you try `omni down`, then deleting the Netdata folder in ~/OmniStream/configs and then `omni up`, followed by `omni update`?

**Comment by shadowsbane0** [comment] 2022-03-08 16:59
It didn’t work. It’s still in a restart loop. I’ll need to dig into the build and see what directories it is trying to access and figure out the permission. Also, is the NetData config directory supposed to be owned by root? When it gets created it is owned by root.

Sent from my iPad
﻿
Sure thing. If it doesn’t work it will be a system permissions issue that I’m still working to find out everywhere it is broken.

For instance Crontab is broken for nonroot user. I fixed the permissions for it but they won’t take effect until I reboot which I can’t do until next week unless you know how to make rsych persist across a reboot and remount of the rclonefs. I’m not keen on starting this synch process over again because it still checks every file even if it doesn’t re-download it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by shadowsbane0** [comment] 2022-03-08 17:09
Are the NetData and sub-directories all supposed to be empty?

Sent from my iPad

﻿ It didn’t work. It’s still in a restart loop. I’ll need to dig into the build and see what directories it is trying to access and figure out the permission. Also, is the NetData config directory supposed to be owned by root? When it gets created it is owned by root.

Sent from my iPad
﻿
Sure thing. If it doesn’t work it will be a system permissions issue that I’m still working to find out everywhere it is broken.

For instance Crontab is broken for nonroot user. I fixed the permissions for it but they won’t take effect until I reboot which I can’t do until next week unless you know how to make rsych persist across a reboot and remount of the rclonefs. I’m not keen on starting this synch process over again because it still checks every file even if it doesn’t re-download it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by shadowsbane0** [comment] 2022-03-08 17:23
On a side note. How are you inserting the plex claim token with this ecosystem? Documentation was thin on that setup.

Sent from my iPad

On Mar 8, 2022, at 12:09, Brian Curry ***@***.***> wrote:

﻿ Are the NetData and sub-directories all supposed to be empty?

Sent from my iPad

﻿ It didn’t work. It’s still in a restart loop. I’ll need to dig into the build and see what directories it is trying to access and figure out the permission. Also, is the NetData config directory supposed to be owned by root? When it gets created it is owned by root.

Sent from my iPad
﻿
Sure thing. If it doesn’t work it will be a system permissions issue that I’m still working to find out everywhere it is broken.

For instance Crontab is broken for nonroot user. I fixed the permissions for it but they won’t take effect until I reboot which I can’t do until next week unless you know how to make rsych persist across a reboot and remount of the rclonefs. I’m not keen on starting this synch process over again because it still checks every file even if it doesn’t re-download it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TechPerplexed** [comment] 2022-03-08 17:41
NetData: hmmm, not sure then... I'll leave that to the brain (aka @kelinger ) 🤣 

As for Plex, it's coming, it's coming.... just not finalized yet in Omni. Right now I'm afraid it still only works with an existing (imported) Plex container... but the Gooby one would do for sure!

**Comment by shadowsbane0** [comment] 2022-03-09 00:22
My main problem on Plex was that I deleted the temporary server that popped up in the web account. That killed the token for my backup. Once it was gone from the Plex.TV end it didn’t matter if I had the backup preference.xml because that token was no longer valid.

What I did to fix it: I opened the claim token site in a small pop up window, I also opened the plex yaml in a text editor. I added in a line to the environment section “PLEX_CLAIM=“. I left the file open in the text editor Geany in my case. Opened Omni MenuI shutdown the plex server from with “docker stop plex”. Deleted the plex directory from Omni config.

Made the magic happened. I clicked to generate a token, copied it to clipboard, hit the text editor and pasted the token after “PLEX_CLAIM=“, control S to save it, omni up, for docker-compose to pick it back up. Open server in web browser. Done and Done….well almost. I still have to restore my backup database and metadata so I don’t have to wait a month for it to rescan the library and create the skip intros.

It took two tries because you have to use the whole string you copy from the plex claim token site to include the “claim” part of the string. Second time it worked. I haven’t looked yet but I’ll be pretty certain Plex.TV issued a different token after accepting the claim token.

As I thought about it and looked at how you did it in Gooby, could you not nest a script in to the omni components script that says “if plex” then prompt for claim, send to your answer variable you use for building the .env file? Then a PLEXCLAIM statement in the yaml can pick up the variable from the .env file.

Anyway my 1/2 cent. Thinking is easy, its the doing that’s hard.


Sent from my iPad

On Mar 8, 2022, at 12:41, Tech Perplexed ***@***.***> wrote:

﻿

NetData: hmmm, not sure then... I'll leave that to the brain (aka @kelinger<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkelinger&data=04%7C01%7C%7Cb90e9d1c1c934d09625808da012aea19%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823581076930421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OcOBR9Ytw2vpjUrjB7qGrz2tzyYs%2FpNqBdkiO9D6uVg%3D&reserved=0> ) 🤣

As for Plex, it's coming, it's coming.... just not finalized yet in Omni. Right now I'm afraid it still only works with an existing (imported) Plex container... but the Gooby one would do for sure!

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkelinger%2FOmniStream%2Fissues%2F2%23issuecomment-1062035698&data=04%7C01%7C%7Cb90e9d1c1c934d09625808da012aea19%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823581076930421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qiTtu2Zb8J5wp1YKXtrg6CfzWzBPQYtWbi%2FIlJTikY4%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGEIJUJZTAGH7EIPSALU66GNRANCNFSM5QGVNZCQ&data=04%7C01%7C%7Cb90e9d1c1c934d09625808da012aea19%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823581076930421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Hx1xP1c09kByLxB0V0yF9yLVUKANct5clNg%2B7125AA0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cb90e9d1c1c934d09625808da012aea19%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823581076930421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0E3O0SbsrPSSG1W0UeNgh54NqBoAPGejwy%2BNDmboWEs%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cb90e9d1c1c934d09625808da012aea19%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823581076930421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X7TTle4Vg2qEV1PfsXGnLLAe6ghc7fSrbUYxWFhg1Xg%3D&reserved=0>.

**Comment by TechPerplexed** [comment] 2022-03-09 01:06
I'm glad it worked for you :) And as I said, it's absolutely going to be added just like with Gooby and I am sure your pointers/suggestions are going to be helpful.

Heads up for next time: the moment you restore your Plex backup, it would be active fully automatically. I have restored Plex on heck knows how new servers and no need to activate any token. It truly is only needed when you want to start from scratch.

**Comment by kelinger** [comment] 2022-03-09 05:05
Try this and let me know what happens:

```
omni down
sudo chown -R $USERID:$GROUPID ${CONFIGS}/netdata
omni up
```

Does netdata work now?

**Comment by kelinger** [comment] 2022-03-09 05:06
Not all containers allow for configuring the in-container user and I believe that netdata was one of them.  I must have changed the ownership of the configs at some point, though, because mine were assigned to me and not root but I definitely see them as root when I start fresh.  Try the previous comment and let us know what happens.

**Comment by shadowsbane0** [comment] 2022-03-09 17:13
Negative on Netdata. I did end up rebooting just to see if it was a process that needed to be restarted. I’m pretty sure it’s something on my end because even though I’ve tired all of the fixes I could find my non root users does not have access to crontab. It makes me wonder what else it doesn’t have access to. I’m half tempted to create another user account, back up my home directory and copy the data back. I can snapshot home before I try it.

Ombi now works. Jellyfin and Emby still won’t come up on standard image pull so I’ll keep using the alternative custom yaml. I’m using hotio for Jellyfin and linuxserver for Emby. hotio’s stuff has been pretty solid for me on the image builds I use.

 I didn’t want to link it because I didn’t want to create an inadvertent developer relationship for you guys.

Sent from my iPhone

On Mar 9, 2022, at 12:06 AM, Ken Linger ***@***.***> wrote:

﻿

Not all containers allow for configuring the in-container user and I believe that netdata was one of them. I must have changed the ownership of the configs at some point, though, because mine were assigned to me and not root but I definitely see them as root when I start fresh. Try the previous comment and let us know what happens.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkelinger%2FOmniStream%2Fissues%2F2%23issuecomment-1062558445&data=04%7C01%7C%7C3495265d3d0d45a535b508da018a9fdc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823992138442269%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rKcvZxF9VaTFZNxe32zeOxJPTRvFlJ9M8tRJ9jIJv6E%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGEFNHDPIKFMDBC6UZTU7AWWZANCNFSM5QGVNZCQ&data=04%7C01%7C%7C3495265d3d0d45a535b508da018a9fdc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823992138442269%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9fHTvNljzXEB8VIkV31trhWaHvY3jV2HXy7ujNlkW%2F8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C3495265d3d0d45a535b508da018a9fdc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823992138442269%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uVceDk5VDRtPU2o7qvz%2BSXPSu8S%2B5ykUYQTGSICRDgA%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C3495265d3d0d45a535b508da018a9fdc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823992138442269%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7bKqveGPjANh7jV9mZdFGR4wgLIroz2UjML%2FG88puIo%3D&reserved=0>.

**Comment by TechPerplexed** [comment] 2022-03-11 15:09
Have you made any progress on Netdata, @shadowsbane0? I'd love to say "NO ONE else experiences this issue, so it must be you..." but then again with just three users (so far, I think), that is rather anecdotal :)

But all joking aside, neither of us can reproduce this issue so is it okay if I close this hoping yours will present a solution all by itself soon?

**Comment by shadowsbane0** [comment] 2022-03-11 15:33
Yes go ahead and close. When I get done with my media transfer off of GSuite in a week or two I’ll worry about troubleshooting it further. I make have to back up and reinstall my Debian.

When I was first installing in on BTRFS I wanted my VAR directory  on a subvol for snapshotting since ATT Inaas using Gooby since that’s where the main features lived. After I set it up on the first reboot it came up and I started adding back apps. I went to take a snapshot and found other than root and home the other subvols didn’t mount. LSS I had to fix fstab and copy over the files while on livecd boot.

I guarantee there are some permission issues all over the place. Since my media content is going on a separate array I can clear and rebuild the system. Likely on the little brother of the host like I’ve mentioned. It’s only little because 17” laptops aren’t REALLY laptops and it’s newer twin, I bought in 15”.

Sent from my iPhone

On Mar 11, 2022, at 10:09 AM, Tech Perplexed ***@***.***> wrote:

﻿

Have you made any progress on Netdata, @shadowsbane0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshadowsbane0&data=04%7C01%7C%7C118a8efa779041d4735008da037125bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637826081742141820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=INZBJJLTmjWh%2BC%2FL%2B3Is03HuqFRDH%2B5nS0ozszgAZPM%3D&reserved=0>? I'd love to say "NO ONE else experiences this issue, so it must be you..." but then again with just three users (so far, I think), that is rather anecdotal :)

But all joking aside, neither of us can reproduce this issue so is it okay if I close this hoping yours will present a solution all by itself soon?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkelinger%2FOmniStream%2Fissues%2F2%23issuecomment-1065200751&data=04%7C01%7C%7C118a8efa779041d4735008da037125bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637826081742141820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DI0ZKvK4laRwCWburf7rbuEe8XT1DJhW65C1vre2DMk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGEFIEBEU72UQP5QOFDU7NO2XANCNFSM5QGVNZCQ&data=04%7C01%7C%7C118a8efa779041d4735008da037125bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637826081742141820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AFgp1A%2Ffbr6MhVRbxvg%2FNG9HEGDosX6gqBBEfnIn0UY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C118a8efa779041d4735008da037125bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637826081742141820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ENSGYxkMxcSyt495fqd1tg98w4%2F%2FjLqKnLHjZ4YaMZE%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C118a8efa779041d4735008da037125bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637826081742141820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F1xRlUF4m4PbAEYH7e%2BkwFf9R1PAu5LNSgkr9RREDOo%3D&reserved=0>.

**Comment by TechPerplexed** [comment] 2022-03-11 15:36
Sounds good! By then we can always revisit the topic if needed... but yeah I tend to agree that it's probably some odd permission issue with your setup 😄

**Closed by TechPerplexed** 2022-03-11 15:36 UTC

**Comment by shadowsbane0** [comment] 2022-10-11 07:58
Sure thing. If it doesn’t work it will be a system permissions issue that I’m still working to find out everywhere it is broken.

For instance Crontab is broken for nonroot user. I fixed the permissions for it but they won’t take effect until I reboot which I can’t do until next week unless you know how to make rsych persist across a reboot and remount of the rclonefs. I’m not keen on starting this synch process over again because it still checks every file even if it doesn’t re-download it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by shadowsbane0** [comment] 2022-10-11 08:46
It was around 5 am and I was tired not thinking after being up all night tinkering.

I like what you did with the 800 personal yamls having omni components pick them up for activation and deactivation – very nice.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
